version: "3"

services:
  # Nacos 服务
  nacos-server:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos-server
    environment:
      - MODE=standalone
      - JVM_XMS=512m
      - JVM_XMX=512m
      - NACOS_AUTH_ENABLE=false
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./data/nacos/logs:/home/nacos/logs
    networks:
      - seckill-network

  # Redis 服务
  redis-server:
    image: redis:7.2
    container_name: redis-server
    ports:
      - "6379:6379"
    command: redis-server --requirepass ""
    volumes:
      - ./data/redis/data:/data
    networks:
      - seckill-network

  # RabbitMQ 服务
  rabbitmq-server:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - seckill-network

  # MySQL 服务
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=seckill
      - MYSQL_USER=seckill
      - MYSQL_PASSWORD=seckill
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - seckill-network

  # XXL-JOB 调度中心
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.0
    container_name: xxl-job-admin
    ports:
      - "8080:8080"
    environment:
      - PARAMS=--spring.datasource.url=jdbc:mysql://mysql-server:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=root
    depends_on:
      - mysql-server
    networks:
      - seckill-network

  # Gateway 服务 - 使用本地JAR文件
  gateway-service:
    image: docker.io/openjdk:17-slim
    container_name: gateway-service
    ports:
      - "9000:9000"
    volumes:
      - ./gateway/target/gateway-0.0.1-SNAPSHOT.jar:/app/app.jar
    command:
      [
        "java",
        "-Dspring.cloud.nacos.discovery.server-addr=nacos-server:8848",
        "-Dspring.cloud.nacos.discovery.username=",
        "-Dspring.cloud.nacos.discovery.password=",
        "-jar",
        "/app/app.jar",
        "--spring.profiles.active=docker",
      ]
    depends_on:
      - nacos-server
      - redis-server
    networks:
      - seckill-network

  # User 服务 - 使用本地JAR文件
  user-service:
    image: docker.io/openjdk:17-slim
    container_name: user-service
    ports:
      - "9001:9001"
    volumes:
      - ./user/target/user-0.0.1-SNAPSHOT.jar:/app/app.jar
    command:
      [
        "java",
        "-Dspring.cloud.nacos.discovery.server-addr=nacos-server:8848",
        "-Dspring.cloud.nacos.discovery.username=",
        "-Dspring.cloud.nacos.discovery.password=",
        "-jar",
        "/app/app.jar",
        "--spring.profiles.active=docker",
      ]
    depends_on:
      - nacos-server
      - mysql-server
      - redis-server
    networks:
      - seckill-network

  # Product 服务 - 使用本地JAR文件
  product-service:
    image: docker.io/openjdk:17-slim
    container_name: product-service
    ports:
      - "9002:9002"
    volumes:
      - ./product/target/product-0.0.1-SNAPSHOT.jar:/app/app.jar
    command:
      [
        "java",
        "-Dspring.cloud.nacos.discovery.server-addr=nacos-server:8848",
        "-Dspring.cloud.nacos.discovery.username=",
        "-Dspring.cloud.nacos.discovery.password=",
        "-jar",
        "/app/app.jar",
        "--spring.profiles.active=docker",
      ]
    depends_on:
      - nacos-server
      - mysql-server
      - redis-server
      - rabbitmq-server
    networks:
      - seckill-network

  # Order 服务 - 使用本地JAR文件
  order-service:
    image: docker.io/openjdk:17-slim
    container_name: order-service
    ports:
      - "9003:9003"
    volumes:
      - ./order/target/order-0.0.1-SNAPSHOT.jar:/app/app.jar
    command:
      [
        "java",
        "-Dspring.cloud.nacos.discovery.server-addr=nacos-server:8848",
        "-Dspring.cloud.nacos.discovery.username=",
        "-Dspring.cloud.nacos.discovery.password=",
        "-jar",
        "/app/app.jar",
        "--spring.profiles.active=docker",
      ]
    depends_on:
      - nacos-server
      - mysql-server
      - redis-server
      - rabbitmq-server
    networks:
      - seckill-network

  # Job 服务 - 使用本地JAR文件
  job-service:
    image: docker.io/openjdk:17-slim
    container_name: job-service
    ports:
      - "9004:9004"
    volumes:
      - ./job/target/job-0.0.1-SNAPSHOT.jar:/app/app.jar
    command:
      [
        "java",
        "-Dspring.cloud.nacos.discovery.server-addr=nacos-server:8848",
        "-Dspring.cloud.nacos.discovery.username=",
        "-Dspring.cloud.nacos.discovery.password=",
        "-jar",
        "/app/app.jar",
        "--spring.profiles.active=docker",
      ]
    depends_on:
      - nacos-server
      - redis-server
      - rabbitmq-server
      - xxl-job-admin
    networks:
      - seckill-network

networks:
  seckill-network:
    driver: bridge
